### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Rohlik** [chkal/rocket-chat-notifier#2]
My build failed. You can see error below. Can you help me?
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:31 min
[INFO] Finished at: 2017-01-12T15:10:55+01:00
[INFO] Final Memory: 22M/63M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project rocket-chat-notifier: Could not resolve dependencies for project de.chkal.jenkins:rocket-chat-notifier:hpi:1.0-SNAPSHOT: Could not find artifact com.github.baloise:rocket-chat-rest-client:jar:master-05801b5f64-1 in jitpack.io (https://jitpack.io) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by chkal** [comment]
Hi,

I'm currently working on a major update of the plugin. Basically because I just discovered, that the plugin doesn't work with recent Rocket.Chat versions. The new version doesn't use the REST API any more and therefore also removes this dependency, which is causing the build failure. After the update, the plugin uses incoming webhooks, which seems to work much better.

I guess I'll push the updated source tomorrow. So I recommend to retry it afterwards.

I'll ping you after I pushed the changes.

Christian

**Comment by chkal** [comment]
I just pushed the latest version... I should work fine with recent Rocket.Chat versions.

Please note that the plugin now uses a webhook for posting messages to Rocket.Chat. So you will have to adjust your configuration accordingly.

Feedback is welcome. I still have to update the README regarding the latest changes.

**Comment by Rohlik** [comment]
Everything works fine. Thx for fix.
PS: Will you add options to enable notification for user specific projects and also for success build?

**Comment by chkal** [comment]
For our use case the plugin is more or less feature complete. But every pull request is welcome.
